'use client'

import { useState, useEffect, useCallback } from 'react'
import { useWorkspace } from '@/providers/WorkspaceProvider'
import { AlertsPanel } from '@/components/analytics/AlertsPanel'
import { RefreshCw, Bell, Zap } from 'lucide-react'
import type { CampaignAlert } from '@/lib/alerts'

export default function AlertsPage() {
  const { currentWorkspace } = useWorkspace()
  const [alerts, setAlerts] = useState<CampaignAlert[]>([])
  const [loading, setLoading] = useState(true)
  const [hasData, setHasData] = useState(false)
  const [message, setMessage] = useState('')
  const [generating, setGenerating] = useState(false)

  const fetchAlerts = useCallback(async () => {
    if (!currentWorkspace) return

    setLoading(true)
    try {
      const response = await fetch(`/api/alerts?workspace_id=${currentWorkspace.id}&status=all`)
      const data = await response.json()

      const mapped = (data.alerts || []).map((a: any) => ({
        id: a.id,
        campaignId: a.campaign?.campaign_id || a.campaign_id,
        campaignName: a.campaign?.name || 'Unknown',
        alertType: a.alert_type,
        severity: a.severity,
        title: a.title,
        message: a.message,
        metricName: a.metric_name,
        metricValue: a.metric_value,
        thresholdValue: a.threshold_value,
        previousValue: a.previous_value,
        status: a.status,
        createdAt: a.created_at,
      }))

      setAlerts(mapped)
      setHasData(data.hasData)
      setMessage(data.message || '')
    } catch (error) {
      console.error('Error fetching alerts:', error)
      setHasData(false)
      setMessage('Failed to load alerts')
    } finally {
      setLoading(false)
    }
  }, [currentWorkspace])

  const generateAlerts = useCallback(async () => {
    if (!currentWorkspace) return

    setGenerating(true)
    try {
      const response = await fetch(`/api/alerts?workspace_id=${currentWorkspace.id}`, {
        method: 'POST',
      })
      const data = await response.json()

      if (response.ok) {
        await fetchAlerts()
      }
    } catch (error) {
      console.error('Error generating alerts:', error)
    } finally {
      setGenerating(false)
    }
  }, [currentWorkspace, fetchAlerts])

  useEffect(() => {
    fetchAlerts()
  }, [fetchAlerts])

  const handleResolve = (id: string) => {
    setAlerts((prev) => prev.filter((a) => a.id !== id))
  }

  const handleDismiss = (id: string) => {
    setAlerts((prev) => prev.filter((a) => a.id !== id))
  }

  return (
    <div className="max-w-6xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-white">Campaign Alerts</h1>
          <p className="text-slate-400 mt-1">Automatic detection of performance issues and anomalies</p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={generateAlerts}
            disabled={generating}
            className="flex items-center gap-2 bg-amber-600 hover:bg-amber-500 disabled:bg-amber-600/50 text-white text-sm px-4 py-2 rounded-lg transition-colors"
          >
            <Zap className={`w-4 h-4 ${generating ? 'animate-pulse' : ''}`} />
            {generating ? 'Scanning...' : 'Run Alert Scan'}
          </button>
          <button
            onClick={fetchAlerts}
            disabled={loading}
            className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            Refresh
          </button>
        </div>
      </div>

      {/* Info banner */}
      <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-4 mb-6">
        <div className="flex items-start gap-3">
          <Bell className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-sm text-slate-300">
              Alerts are automatically generated by comparing current period (last 7 days) vs previous period.
              Duplicate alerts are prevented within configurable time windows per alert type.
              Click &quot;Run Alert Scan&quot; to manually trigger detection.
            </p>
          </div>
        </div>
      </div>

      {/* Alerts */}
      <AlertsPanel
        alerts={alerts}
        loading={loading}
        hasData={hasData}
        message={message}
        onResolve={handleResolve}
        onDismiss={handleDismiss}
      />
    </div>
  )
}
